function [fitresult, gof] = createFit(timeInterval, angleInterval)
%CREATEFIT(TIMEINTERVAL,ANGLEINTERVAL)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : timeInterval
%      Y Output: angleInterval
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Apr-2018 20:20:00


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( timeInterval, angleInterval );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
%figure( 'Name', 'untitled fit 1' );
%h = plot( fitresult, xData, yData );
%legend( h, 'angleInterval vs. timeInterval', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
%xlabel timeInterval
%ylabel angleInterval
%grid on


